# Bukkit/Spigot

name: XoreBoardUtil
main: net.minecord.xoreboardutil.bukkit.XoreBoardUtil
version: ${project.version}
description: Virtual Scoreboard API based on packets with no dependencies
author: misuda12
authors:
  - haelexuis
website: http://www.minecord.net/projects/XoreBoardUtil